on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

name: Test

jobs:
  freebsd:
    strategy:
      matrix:
        release:
          - "14.3"
          - "15.0"
    if: github.repository == 'jcollie/ghostty'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Test in FreeBSD
        id: test
        uses: vmactions/freebsd-vm@05856381fab64eeee9b038a0818f6cec649ca17a # v1.2.3
        with:
          release: ${{ matrix.release }}
          prepare: |
            pkg install -y \
              zig \
              blueprint-compiler \
              gtk40 \
              gtk4-layer-shell \
              pandoc \
              pkg-config \
              wayland

          run: |
            pwd
            ls -lah
            whoami
            env
            freebsd-version
            sysctl hw.model
            sysctl hw.ncpu
            sysctl hw.physmem
            sysctl hw.usermem
            zig env
            zig build test
            zig build
